Revert "feat: add user context to lapsoss error tracking"
This reverts commit 70fcef5dd3bb3405251a11f197be94a2599ced57.

I get this error in development:

```
NoMethodError (undefined method 'action_name' for an instance of String):

app/controllers/web_apps_controller.rb:10:in 'WebAppsController#index'
```